# Generated by Django 3.2.16 on 2022-10-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hod', models.CharField(max_length=100)),
                ('hod_email', models.EmailField(max_length=254)),
                ('hod_ph', models.IntegerField()),
            ],
        ),
    ]
