# Generated by Django 3.2.16 on 2022-10-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freezing_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_t', models.TimeField()),
                ('after_t', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Time_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.DateTimeField()),
                ('exclusion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('controller', models.CharField(max_length=100)),
                ('cont_ph', models.IntegerField()),
                ('cont_email', models.EmailField(max_length=254)),
                ('availability', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
