# Generated by Django 3.2.16 on 2022-10-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('start_td', models.DateTimeField()),
                ('end_td', models.DateTimeField()),
                ('agenda', models.TextField()),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('minutes', models.TextField()),
                ('vunue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.venue')),
            ],
        ),
    ]
